github: https://github.com/sureshfizzy/CineSync
patreon: https://www.patreon.com/c/sureshs/membership
buy_me_a_coffee: https://www.buymeacoffee.com/Sureshfizzy
paypal: https://www.paypal.me/sureshfizzy
